const filter1 = {};
const filter2 = {};const projection2 = {  'restaurant_id': 1,   'name': 1,   'borough': 1,   'cuisine': 1};
const filter3 = {};const projection3 = {  'restaurant_id': 1,   'name': 1,   'borough': 1,   'cuisine': 1,   '_id': 0};
const filter4 = {};const projection4 = {  'restaurant_id': 1,   'name': 1,   'borough': 1,   'address.zipcode': 1,   '_id': 0};
const filter5 = {'borough': 'Bronx'};
const filter6 = {'borough': 'Bronx'};const limit6 = 5;
const filter7 = {'borough': 'Bronx'};const skip7 = 5;const limit7 = 5;
const filter8 = {'grades': {'$elemMatch': {'score': {'$gte': 90}}}};
const filter9 = {'grades': {'$elemMatch': {'score': {'$gte': 80, '$lte': 100}}}};
const filter10 = {'address.coord.0': {'$lt': -95.754168}};
const filter11 = {'address.coord.0': {'$lt': -65.754168}, 'cuisine': { '$ne': 'American '}, 'grades.score': {'$gt': 70}};
const filter12 = {'address.coord.1': {'$lt': 65.754168}, 'cuisine': {'$ne': 'American '}, 'grades.score': {'$gt': 70}};
const filter13 = {'borough': {'$ne': 'Brooklyn'}, 'cuisine': {'$ne': 'American '}, 'grades.grade': 'A'};const sort = {'cuisine': -1};
const filter14 = {'name': { '$regex': new RegExp('^Wil')}}; const projection14 = {'restaurant_id': 1, 'name': 1, 'borough': 1, 'cuisine': 1, '_id': 0}; 
const filter15 = {'name': {'$regex': new RegExp('ces$')}};
const filter16 = {'name': {'$regex': 'Reg'}}; const projection16 = {'restaurant_id': 1, 'name': 1, 'borough': 1, 'cuisine': 1, '_id': 0};
const filter17 = {'$and': [{ 'borough': 'Brooklyn'}, { '$or': [ { 'cuisine': 'American ' }, { 'cuisine': 'Chinese'}]}]};
const filter18 = {'$or': [{'borough': 'Staten Island'}, {'borough': 'Queens'}, {'borough': 'Brooklyn'}, {'borough': 'Bronx'}]};const projection18 = {'restaurant_id': 1, 'name': 1, 'borough': 1, 'cuisine': 1, '_id': 0};
const filter19 = {'$nor': [{'borough': 'Staten Island'}, {'borough': 'Queens'}, {'borough': 'Brooklyn'}, {'borough': 'Bronx'}]};const projection19 = {'restaurant_id': 1, 'name': 1, 'borough': 1, 'cuisine': 1, '_id': 0};
const filter20 = { 'grades': { '$elemMatch': {'score': {'$lt': 10}}}};const projection20 = { 'restaurant_id': 1, 'name': 1, 'borough': 1, 'cuisine': 1,'_id': 0};
const filter22 = {'$and': [{'grades.grade': 'A'}, {'$and': [{'grades.score': 11}, {'grades.date': new Date('Mon, 11 Aug 2014 00:00:00 GMT')}]}]};const projection22 = {'restaurant_id': 1, 'name': 1, 'grades': 1, '_id': 0};
const filter23 = {'$and': [{ 'grades.1.grade': 'A'}, {'grades.1.score': 9}, { 'grades.1.date': new Date('Mon, 11 Aug 2014 00:00:00 GMT')}]}; const projection23 = {'restaurant_id': 1, 'name': 1, 'grades': 1, '_id': 0};
const filter24 = {'address.coord.1': {'$gte': 42, '$lte': 52}}; const projection24 = {'restaurant_id': 1, 'name': 1, 'address': 1, '_id': 0};
const filter25 = {}; const sort25 = {'name': 1}; 
const filter26 = {}; const sort26 = {'name': -1}; 
const filter27 = {}; const sort27 = { 'cuisine': 1, 'borough': -1};
const filter28 = { 'address.street': { '$regex': new RegExp('Street')}};
const filter31 = {'name': {'$regex': new RegExp('mon')}}; const projection31 = {'restaurant_id': 1, 'name': 1, 'address.coord': 1, 'cuisine': 1, '_id': 0};
const filter32 = {'name': { '$regex': new RegExp('^Mad')}}; const projection32 = {'restaurant_id': 1, 'name': 1, 'address.coord': 1, 'cuisine': 1, '_id': 0};

